#!/bin/sh

screenlock() {
  i3lock -i ~/.i3/i3locked1366x768.png
}

case "$1" in
  lock)
    screenlock
    ;;
  logout)
    i3-msg exit
    ;;
  suspend)
    screenlock && systemctl suspend
    ;;
  hibernate)
    screenlock && systemctl hibernate
    ;;
  reboot)
    systemctl reboot
    ;;
  shutdown)
    systemctl poweroff
    ;;
  *)
    echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
    exit 2
esac

exit 0
